auto: true

markdown: kramdown
highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Publius' Blog”
title: Publius' Blog
description: Everything about Publius.
url: http://kiko626.github.io
#feed: /atom.xml
author_info: <a href="http://kiko626.github.io">Publius</a>
