auto: true

markdown: kramdown
highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Kikosame's Blog”
title: Kikosame's Blog
description: Everything about Kikosamei.
url: http://kiko626.github.io
feed: /atom.xml
author_info: <a href="http://kiko626.github.io">Kikosame</a>
