auto: true

markdown: kramdown
highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Kikofloat's Blog”
title: Kikofloat's Blog
description: Everything about Kikofloat.
url: http://kiko626.github.io
#feed: /atom.xml
author_info: <a href="http://kiko626.github.io">Kikofloat</a>
